In [7]:
import pandas as pd
import numpy as np 
import warnings
warnings.filterwarnings("ignore")

from matplotlib import pyplot as plt
from sklearn import linear_model

In [8]:
df = pd.read_csv('meteo.csv')
df.head()

,Unnamed: 0,index,Kod stacji,Nazwa stacji,Rok,Miesiąc,Dzień,Maksymalna temperatura dobowa,Status pomiaru TMAX,Minimalna temperatura dobowa,...,Wystąpienie błyskawicy [0/1],Status pomiaru DZBL,Stan gruntu [Z/R],Izoterma dolna [cm],Status pomiaru IZD,Izoterma górna [cm],Status pomiaru IZG,Aktynometria [J/cm2],Status pomiaru AKTN,date
0,0,0,354150100,KOŁOBRZEG,2001,1,1,2.4,NaN,-3.1,...,0,NaN,NaN,0,8.0,0,8.0,0,8.0,2001-01-01
1,1,1,354150100,KOŁOBRZEG,2001,1,2,1.9,NaN,-1.1,...,0,NaN,NaN,0,8.0,0,8.0,0,8.0,2001-01-02
2,2,2,354150100,KOŁOBRZEG,2001,1,3,4.2,NaN,0.1,...,0,NaN,NaN,0,8.0,0,8.0,0,8.0,2001-01-03
3,3,3,354150100,KOŁOBRZEG,2001,1,4,3.9,NaN,0.0,...,0,NaN,NaN,0,8.0,0,8.0,0,8.0,2001-01-04
4,4,4,354150100,KOŁOBRZEG,2001,1,5,4.8,NaN,0.5,...,0,NaN,NaN,0,8.0,0,8.0,0,8.0,2001-01-05

In [41]:
#Tablica w ktorej beda dataFrame'y z kazdego miesiaca
dataFrames = []
#Tablica miesiecy do podpisania wykresow
months = ['Styczeń','Luty','Marzec','Kwiecień','Maj','Czerwiec','Lipiec','Sierpień','Wrzesień','Październik','Listopad','Grudzień']

for i in range(0,12):
    #Wyróżnienie tylko Toruńskiej stacji pogodowej w danym miesiącu
    dataFrames.append(df[(df["Nazwa stacji"]=="TORUŃ") & (df["Miesiąc"] == i+1)])
    #Wyznaczenie kolumny z datą jako głównego indeksu
    dataFrames[i] = dataFrames[i].set_index(dataFrames[i].date)
    #Wyciągniecie sredniej temp w kazdym roku
    dataFrames[i] = dataFrames[i].groupby(by=dataFrames[i]["Rok"]).mean()
    #Wyznaczenie x i y do regresji liniowej
    X = dataFrames[i].index
    Y = dataFrames[i]["Średnia temperatura dobowa"]
    #Regresja wielomianowa 1 stopnia - liniowa
    #Funkcja przyjmuje dwa wektory, współrzędne punktów: x i y, które powinny mieć taką samą liczbę
    #elementów. Argument k (tutaj 1) określa stopień wielomianu, który ma te podane punkty aproksymować
    #(przybliżyć funkcję za pomocą wielomianu).
    #Zwracany wektor zawiera współczynniki przy odpowiednich potęgach zmiennej x
    b1,b2 = np.polyfit(X,Y,1) 
    #y=ax+b
    #Dodanie DataFramu z przyszłymi latami
    X2 = X.insert(len(X),[2022,2023,2024,2025,2026,2027])
    y_lin = b2+b1*X2
    #Wyrysowanie wykresow
    dataFrames[i]["Średnia temperatura dobowa"]\
        .plot(xticks=X2,fontsize=10,rot=90,title=months[i],xlabel="ROK",ylabel="TEMPERATURA",figsize=(10,7),label="Avg")\
        .legend(loc='upper right')
    plt.plot(X2, y_lin, 'g--', label='Lin_reg')
    #Zapisanie figur w plikach png
    plt.savefig("MiesiacV2_reg" + str(i+1) + ".png")
    #Wyczyszczenie po kazdym wyrysowaniu figury na dany miesiac zeby dane nie zbieraly sie tylko na 1 rysunku
    plt.clf()